# Generated by Django 5.1.6 on 2026-06-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_first_name_alter_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='theme',
            field=models.CharField(choices=[('light', 'Светлая'), ('dark', 'Темная')], default='light', max_length=10, verbose_name='Тема интерфейса'),
        ),
    ]
