# Generated by Django 5.1.6 on 2025-02-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_customuser_first_name_alter_customuser_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="patronymic",
            field=models.CharField(max_length=150, verbose_name="Отчество"),
        ),
    ]
