services:
  web:
    image: cr.yandex/crp2hgrg6imtfn9h9lpi/siz_manager:1.0.8
    env_file: .env.prod
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/manager
      - DJANGO_SETTINGS_MODULE=manager.settings
      - SQLITE_TIMEOUT=60
      - SQLITE_MMAP_SIZE=268435456
      - SQLITE_JOURNAL_MODE=WAL
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health/ || exit 1"]
      interval: 300s
      timeout: 10s
      retries: 3
      start_period: 120s
    logging:
      options:
        max-size: "20m"
        max-file: "5"
    command: >
      bash -c "
        python manager/manage.py migrate --noinput &&
        exec gunicorn --bind 0.0.0.0:8000 --workers 3 --threads 2 --pythonpath manager --preload manager.wsgi:application
      "
    volumes:
      - persistent_data:/app/manager/data:rw,cached
      - static_volume:/app/manager/staticfiles:ro
      - media_volume:/app/manager/media:rw,cached
      - backup_volume:/app/backups:rw
    networks:
      - backend
    restart: unless-stopped  # Auto-restart policy

  nginx:
    image: nginx:1.28
    ports:
      - "80:80"
    volumes:
      - ./nginx-prod.conf:/etc/nginx/conf.d/default.conf  # Absolute path to config
      - static_volume:/var/www/staticfiles
      - media_volume:/var/www/media
    depends_on:
      - web
    networks:
      - backend
    restart: unless-stopped

volumes:
  persistent_data:
  static_volume:
  media_volume:
  backup_volume:

networks:
  backend:
