# Generated by Django 5.1.6 on 2025-02-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ppetype",
            name="default_mu",
            field=models.CharField(
                choices=[
                    ("шт.", "штук"),
                    ("пар.", "пар"),
                    ("компл.", "комплектов"),
                    ("г.", "грамм"),
                    ("мл.", "миллилитров"),
                ],
                default="шт.",
                max_length=10,
                verbose_name="Единица измерения",
            ),
        ),
    ]
