# Generated by Django 5.1.6 on 2025-02-20 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issues",
                to="core.item",
                verbose_name="СИЗ",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="ppe_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="core.ppetype",
                verbose_name="Тип СИЗ",
            ),
        ),
        migrations.AlterField(
            model_name="norm",
            name="ppe_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="norms",
                to="core.ppetype",
                verbose_name="Тип СИЗ",
            ),
        ),
        migrations.AlterField(
            model_name="norm",
            name="quantity",
            field=models.PositiveIntegerField(
                help_text="Сколько единиц СИЗ положено для этой должности",
                verbose_name="Количество",
            ),
        ),
    ]
