# Generated by Django 5.1.6 on 2025-02-20 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_issue_item_alter_item_ppe_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="norm",
            name="ppe_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="norms",
                to="core.ppetype",
            ),
        ),
    ]
