# Generated by Django 2.2.16 on 2025-02-20 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250220_0612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_type',
        ),
        migrations.AddField(
            model_name='issue',
            name='item_type',
            field=models.CharField(default='Ботинки', help_text='Тип СИЗ (например, ботинки, перчатки)', max_length=255, verbose_name='Тип СИЗ'),
        ),
        migrations.AddField(
            model_name='norm',
            name='item_type',
            field=models.CharField(default='Ботинки', help_text='Тип СИЗ (например, ботинки, перчатки)', max_length=255, verbose_name='Тип СИЗ'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='core.Item', verbose_name='СИЗ'),
        ),
        migrations.AlterUniqueTogether(
            name='norm',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='norm',
            name='item',
        ),
    ]
