# Generated by Django 2.2.16 on 2025-04-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_flushingagentissue_is_active_alter_container_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='container',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='container',
            name='agent_type',
        ),
        migrations.RemoveField(
            model_name='container',
            name='employee',
        ),
        migrations.AlterModelOptions(
            name='flushingagentissue',
            options={'ordering': ['issue_date'], 'verbose_name': 'Выдача моющего средства', 'verbose_name_plural': 'Выдачи моющих средств'},
        ),
        migrations.AddField(
            model_name='flushingagentissue',
            name='consumption_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата полного расходования'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='flushingagentissue',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='flushingagentnorm',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='flushingagenttype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='heightgroup',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='norm',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='normheight',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ppetype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='flushingagentissue',
            index=models.Index(fields=['employee', 'agent_type', 'is_active', 'issue_date'], name='core_flushi_employe_030291_idx'),
        ),
        migrations.DeleteModel(
            name='Container',
        ),
    ]
