# Generated by Django 5.1.6 on 2025-04-26 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_flushing_agent_processing"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlushingAgentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "processed_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата обработки"),
                ),
                (
                    "reference_month",
                    models.DateField(
                        help_text="Первый день месяца, за который проводится расчёт",
                        verbose_name="Расчётный месяц",
                    ),
                ),
                (
                    "total_consumed",
                    models.PositiveIntegerField(verbose_name="Всего списано (мл)"),
                ),
                (
                    "agent_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.flushingagenttype",
                        verbose_name="Тип средства",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.employee",
                        verbose_name="Сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Транзакция моющих средств",
                "verbose_name_plural": "Транзакции моющих средств",
            },
        ),
        migrations.CreateModel(
            name="TransactionDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consumed_volume",
                    models.PositiveIntegerField(verbose_name="Списано (мл)"),
                ),
                (
                    "previous_volume",
                    models.PositiveIntegerField(verbose_name="Объём до списания"),
                ),
                ("was_active", models.BooleanField(verbose_name="Было активно")),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.flushingagentissue",
                        verbose_name="Выдача",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="core.flushingagenttransaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Деталь транзакции",
                "verbose_name_plural": "Детали транзакций",
            },
        ),
        migrations.AddIndex(
            model_name="flushingagenttransaction",
            index=models.Index(
                fields=["reference_month", "employee", "agent_type"],
                name="core_flushi_referen_86402b_idx",
            ),
        ),
    ]
