# Generated by Django 5.1.6 on 2025-04-26 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_flushing_agent_processing"),
    ]

    operations = [
        migrations.AddField(
            model_name="flushingagentissue",
            name="volume_ml_nominal",
            field=models.PositiveIntegerField(
                default=200,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Объем (мл)",
            ),
            preserve_default=False,
        ),
    ]
