# Generated by Django 5.1.6 on 2025-02-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_employee_id_alter_issue_id_alter_item_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="item_type",
            field=models.CharField(
                help_text="Тип СИЗ (например, ботинки, перчатки)",
                max_length=255,
                verbose_name="Тип СИЗ",
            ),
        ),
    ]
